# Generated by Django 4.2.30 on 2026-05-15 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email_recipient', models.CharField(max_length=100)),
                ('email_type', models.CharField(max_length=50)),
                ('body', models.JSONField()),
                ('is_sent', models.BooleanField(default=False)),
                ('retries', models.IntegerField()),
                ('email_created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'EMAIL STATUSES',
                'db_table': 'email_status',
                'ordering': ['-id'],
            },
        ),
    ]
