# Generated by Django 4.2.30 on 2026-05-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailstatus',
            old_name='body',
            new_name='email_user',
        ),
    ]
