# Generated by Django 4.2.30 on 2026-05-15 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('profile_phone', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('profile_organization', models.CharField(default='', max_length=9000)),
                ('profile_type', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Organization_Admin', 'Organization Admin')], default='Organization_Admin', max_length=9000)),
                ('profile_is_active', models.BooleanField(db_index=True, default=True)),
                ('profile_created_date', models.DateField(auto_now_add=True)),
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'USER PROFILES',
                'db_table': 'user_profiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SavePasswordRequestUsers',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('save_pswd_token', models.CharField(default=None, editable=False, max_length=300)),
                ('save_pswd_is_used', models.BooleanField(default=False)),
                ('save_pswd_is_active', models.BooleanField(default=True)),
                ('save_pswd_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SAVE PASSWORD REQUESTS',
                'db_table': 'save_password_request',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='ForgotPasswordRequestUser',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('request_token', models.CharField(default=None, editable=False, max_length=300)),
                ('request_is_used', models.BooleanField(default=False)),
                ('request_is_active', models.BooleanField(default=True)),
                ('request_created_date', models.DateTimeField(auto_now_add=True)),
                ('request_expiration_time', models.DateTimeField()),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'FORGOT PASSWORD REQUESTS',
                'db_table': 'users_forgot_password_request',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='ActivateAccountTokenUser',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('token_token', models.CharField(default=None, editable=False, max_length=300)),
                ('token_is_used', models.BooleanField(default=False)),
                ('token_is_active', models.BooleanField(default=True)),
                ('token_created_date', models.DateTimeField(auto_now_add=True)),
                ('token_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ACTIVATE ACCOUNT TOKEN',
                'db_table': 'users_activate_account_token',
                'ordering': ['-primary_key'],
            },
        ),
    ]
